### PR TITLE
Homepage layout mock-up

### PR DESCRIPTION
**Pull request by nikita-1801**
Issue #3 
Created the mock-up for the homepage and added it as a .jpg file

Head section:
header

About section with scroll-down button:
about

Features section:
features
It will be in the form of a circular carousel. 

CTA section and Footer:
footer

In the footer, instead of the letters social media icons will be added. Also, illustrations are just for sample. So, the color scheme depends on the illustrations we choose.

### CODE REVIEW

**Comment by Sonali12920** [comment]
Add all the files of this page design, not .jpg file.

**Comment by nikita-1801** [comment]
> Add all the files of this page design, not .jpg file.

It is a mock-up, I made it on a photo editor.

**Comment by Sonali12920** [comment]
We want a basic homepage to start with. If you can make it then do so. We don't need layout mockup(picture). We need a working homepage ( with all the files).

**Comment by nikita-1801** [comment]
I've added app.js for issue #23 for the setting up of server issue.

**Pull request merged**
